config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                       Controller#Action
#      new_ans GET    /quests/:id/answers/new(.:format) answers#new
#              POST   /quests/:id/answers/new(.:format) answers#create
#  edit_answer GET    /answers/:id/edit(.:format)       answers#edit
#       answer GET    /answers/:id(.:format)            answers#show
#              PATCH  /answers/:id(.:format)            answers#update
#              PUT    /answers/:id(.:format)            answers#update
#              DELETE /answers/:id(.:format)            answers#destroy
# quests_index GET    /quests/index(.:format)           quests#index
#       quests GET    /quests(.:format)                 quests#index
#              POST   /quests(.:format)                 quests#create
#    new_quest GET    /quests/new(.:format)             quests#new
#   edit_quest GET    /quests/:id/edit(.:format)        quests#edit
#        quest GET    /quests/:id(.:format)             quests#show
#              PATCH  /quests/:id(.:format)             quests#update
#              PUT    /quests/:id(.:format)             quests#update
#              DELETE /quests/:id(.:format)             quests#destroy
#         root GET    /                                 quests#index
#        login GET    /login(.:format)                  sessions#new
#              POST   /login(.:format)                  sessions#create
#       logout GET    /logout(.:format)                 sessions#destroy
#       signup GET    /signup(.:format)                 users#new
#        users POST   /users(.:format)                  users#create
#

# /quests -- index of quests
#
# /quests/:id - show a single quest with all answers
#
# /quests/:id/answers/new - create a new answer
#

Rails.application.routes.draw do

  root 'quests#index'

  resources :quests do
    resources :answers
  end

  # namespace :api do
  #     namespace :v1 do
  #       resources :sessions, only: [:create, :show]
  #       resources :users, only: [:index, :create, :show, :update, :destroy] do
  #         quests :activate, on: :collection
  #         resources :followers, only: [:index, :destroy]
  #         resources :followings, only: [:index, :destroy] do
  #           post :create, on: :member
  #         end
  #         resource :feed, only: [:show]
  #       end
  #       resources :microposts, only: [:index, :create, :show, :update, :destroy]
  #     end
  #   end

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'

end

app/models/quest.rb
# == Schema Information
#
# Table name: quests
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Quest < ApplicationRecord
  belongs_to :user
  has_many :answers
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
before_action :my_quest, only: [:edit, :update, :destroy]


  def index
    @quests = Quest.page(params[:page]).per(5)
  end

  def show
    @quest = Quest.find(params[:id])
    @answers = Answer.where(quest_id: @quest.id)
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(quest_params)
    @quest.user = current_user

    if @quest.save
      redirect_to @quest
    else
      render 'new'
    end
  end

  def edit
    @quest = Quest.find(params[:id])
  end

  def update
    @quest = Quest.find(params[:id])
    if @quest.update(quest_params)
      redirect_to @quest
    else
      render 'edit'
    end

  end

  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy!

    redirect_to quests_path
  end

private

  def quest_params
    params.require(:quest).permit(:title, :body, :user_id)
  end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.haml
= form_for @quest do |f|
  - if @quest.errors.any?
    #error_explanation
      %h2
        = pluralize(@quest.errors.count, "error")
        prohibited
        this question from being saved:
      %ul
        - @quest.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :Title
    %br/
    = f.text_field :title
  %p
    = f.label :Body
    %br/
    = f.text_area :body
  %p
    = f.submit :class => "btn btn-primary"

app/views/quests/edit.html.haml
%h1.edit-title Editing the entry for #{@quest.title}!
= render 'form'
= link_to 'Back', quests_path, :class => "btn btn-primary backbutton"

app/views/quests/index.html.haml
%h1.title.jumbotron Stack Joverflow Questions and Maybe Answers Repository
= link_to 'Ask ya damn question!', new_quest_path, :class => "btn btn-primary btn-block"
%br
= paginate @quests
%br
%table.table
  %tr.headrow
    %th.tabhead Title
    %th.tabhead Body

  - @quests.each do |quest|
    %tr.quest-card
      %td= quest.title
      %td= markdown(quest.body)
      %td= link_to 'Show', quest_path(quest), :class => 'btn btn-info'
      %td= link_to 'Answer', new_quest_answer_path(quest), :class => 'btn btn-info'
      - if quest.user == current_user
        %td= link_to 'Edit', edit_quest_path(quest), :class => 'btn btn-info'
        %td= link_to 'Delete', quest_path(quest), :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this question?' }
      %td Last changed #{time_ago_in_words quest.updated_at} ago
= paginate @quests




- if current_user
  %span.status Signed in as #{current_user.username}
  %br
  #{link_to "Logout", '/logout', :class => "status"}
- else
  = link_to 'Login', '/login', :class => "status"
  %br
  #{link_to 'Signup', '/signup', :class => "status"}
= yield

app/views/quests/new.html.haml
%h1.new-title What's your question?
= render 'form'
= link_to 'Back', quests_path, :class => "btn btn-primary"

app/views/quests/show.html.haml
.row
  .col-lg-8.quest-div
    %p.show.show-title
      %strong Title:
      = @quest.title
    %p.show
      %strong Body:
      = @quest.body
    %hr
    - if @quest.user == current_user
      = link_to 'Edit this question', edit_quest_path(@quest), :class => "btn btn-primary"

    = link_to 'Back', quests_path, :class => "btn btn-primary backbutton"

  .col-lg-4
    .ansdiv
      %h3.answers-title Answers
      =flash_messages
    - if @answers != []
      - @answers.each do |ans|
        .card{:style => "width: 40rem;"}
          .card-block
            %h4.card-title #{ans.user.username}
            %hr
            %p.card-text #{ans.body}
        - if ans.user == current_user
          -# = link_to 'Accept Answer', toggle_path[:id], ans, :class => 'btn btn-warning col-md-2'
          = link_to 'Edit', edit_quest_answer_path(quest_id: ans.quest_id, id: ans.id), :class => "btn btn-primary"
          = link_to 'Delete', quest_answer_path(quest_id: ans.quest_id, id: ans.id), method: :delete, data: { confirm: 'Are you sure you want to delete this answer?' }, :class => "btn btn-danger"


    - else
      %h4 No answers yet, hang tight!





-# %h2 Comments
-# = render @article.comments
-# %h2 Add a comment:
-# = render 'comments/form'
%hr